-- Custom SQL migration file, put your code below! --

INSERT INTO `cities` (`id`, `country_code`, `name`) VALUES
(1, 'US', 'New York City'),
(2, 'US', 'Chicago'),
(3, 'CN', 'Hong Kong'),
(4, 'CN', 'Guangzhou'),
(5, 'CN', 'Shenzhen'),
(6, 'CN', 'Kaohsiung'),
(7, 'MY', 'Kuala Lumpur'),
(8, 'CN', 'Shanghai'),
(9, 'AE', 'Dubai'),
(10, 'CN', 'Taipei'),
(11, 'AU', 'Gold Coast'),
(12, 'CN', 'Wuhan'),
(13, 'CN', 'Nanjing'),
(14, 'CN', 'Beijing'),
(15, 'KW', 'Kuwait City'),
(16, 'CN', 'Tianjin'),
(17, 'CN', 'Wuxi'),
(18, 'CN', 'Wenzhou'),
(19, 'SA', 'Mecca'),
(20, 'VN', 'Hanoi'),
(21, 'RU', 'Moscow'),
(22, 'AE', 'Abu Dhabi'),
(23, 'CN', 'Shenyang'),
(24, 'CN', 'Chongqing'),
(25, 'CN', 'Dalian'),
(26, 'CN', 'Kunming'),
(27, 'KR', 'Seoul'),
(28, 'US', 'Los Angeles'),
(29, 'CN', 'Zhuhai'),
(30, 'CN', 'Yantai'),
(31, 'CN', 'Nanning'),
(32, 'VN', 'Ho Chi Minh City'),
(33, 'CN', 'Changsha'),
(34, 'US', 'Philadelphia'),
(35, 'CN', 'Zhenjiang'),
(36, 'US', 'San Francisco'),
(37, 'HU', 'Budapest');